language:
    - python

python:
    - "3.3"

git:
    submodules: false

before_install:
    - sudo apt-get update
    # test integration only, other tests can be found in standalone versions
    - git submodule update --init ./configs ./sugar ./google/gtest ./json/rapidjson
    - "wget https://launchpad.net/ubuntu/+source/cmake/2.8.8-2ubuntu1/+build/3441442/+files/cmake_2.8.8-2ubuntu1_amd64.deb"
    - "wget https://launchpad.net/ubuntu/+archive/primary/+files/cmake-data_2.8.8-2ubuntu1_all.deb"
    - "sudo apt-get remove cmake-data cmake"

install:
    - "sudo dpkg --install cmake-data_2.8.8-2ubuntu1_all.deb cmake_2.8.8-2ubuntu1_amd64.deb"

script:
    # test submodule: configs
    - python configs/setup.py --gitenv-root `pwd` --force
    - source ~/.bashrc # now GITENV_ROOT environment variable can be used
    - which gvim.py # test PATH updated
    - which trash.py # test PATH updated

    # test submodule: gtest
    - cd "${GITENV_ROOT}/google/gtest"
    - cmake .
    - make

    # test submodule: sugar (other tests in sugar standalone, TODO: boost)
    - cd "${GITENV_ROOT}/sugar/examples"
    - python test.py --include ./03-gtest ./09-rapidjson
